# 7.	Write a python program to fit a multiple   regression model for any given data.

In [21]:
import numpy as np

def myMean(data):
    mean = 0
    for i in np.nditer(data):
        mean += i
    mean /= len(data)
    return mean

def det(mat):
    v1 = mat[0,0] * ((mat[1,1] * mat[2,2]) - (mat[1,2] * mat[2,1]))
    v2 = -mat[0,1] * ((mat[1,0] * mat[2,2]) - (mat[1,2] * mat[2,0]))
    v3 = mat[0,2] * ((mat[1,0] * mat[2,1]) - (mat[1,1] * mat[2,0]))
    return v1+v2+v3

def transpose(mat):
    
x1 = np.array([[float(i)] for i in input("Enter x1 values:").split()])
#-5 -4 -1 2 2 3 3

x2 = np.array([[float(i)] for i in input("Enter x2 values:").split()])
#5 4 1 -3 -2 -2 -3

y = np.array([[float(i)] for i in input("Enter y values: ").split()])
#11 11 8 2 5 5 4
print(y)

size = np.shape(x1)
print(size)

ones = np.array(np.ones(size))
print(ones)

x = np.hstack((ones,x1))
x = np.hstack((x,x2))
print(x)

Enter x1 values:-5 -4 -1 2 2 3 3
Enter x2 values:5 4 1 -3 -2 -2 -3
Enter y values: 11 11 8 2 5 5 4
[[11.]
 [11.]
 [ 8.]
 [ 2.]
 [ 5.]
 [ 5.]
 [ 4.]]
(7, 1)
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
[[ 1. -5.  5.]
 [ 1. -4.  4.]
 [ 1. -1.  1.]
 [ 1.  2. -3.]
 [ 1.  2. -2.]
 [ 1.  3. -2.]
 [ 1.  3. -3.]]


In [33]:

mat  = np.array([[[2,0,0],[3,4,5],[6,7,8]]])
print(mat)
 

[[[2 0 0]
  [3 4 5]
  [6 7 8]]]


IndexError: index 1 is out of bounds for axis 0 with size 1